{% set name = "btrack" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantumjot/BayesianTracker/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5cff4042c2be9c2a5f3f35dcf27b9f2e7e916096045ed3721c5401d7f4799417
  patches:
    - makefile.patch
    - eigen_includes.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - pip
    - python
    - eigen
  run:
    - cvxopt >=1.2.0
    - h5py >=2.10.0
    - matplotlib-base >=3.1.1
    - numpy >=1.17.3
    - python
    - scikit-image >=0.16.2
    - scipy >=1.3.1

test:
  imports:
    - btrack
  commands:
    - pip check
    - python -c "from btrack.libwrapper import get_library; print(get_library())"
  requires:
    - pip

about:
  home: https://github.com/quantumjot/BayesianTracker
  summary: A framework for Bayesian multi-object tracking
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - goanpeca
