{% set name = "btrack" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantumjot/BayesianTracker/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 41f65dec33839c31af343192873b7ff1d19f5c90496a20ea91a4f08b6233d67a
  patches:
    - makefile.patch
    - eigen_includes.patch

build:
  number: 0
  skip: true  # [win or py==37]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - pip
    - python
    - eigen
  run:
    - cvxopt >=1.2.0
    - h5py >=2.10.0
    - matplotlib-base >=3.1.1
    - napari >=0.4.16
    - napari-plugin-engine
    - numpy >=1.17.3
    - pooch >=1.0.0
    - pydantic >=1.9.0
    - python
    - scikit-image >=0.16.2
    - scipy >=1.3.1

test:
  imports:
    - btrack
  commands:
    - pip check
    - python -c "from btrack.libwrapper import get_library; print(get_library())"
  requires:
    - pip

about:
  home: https://github.com/quantumjot/BayesianTracker
  summary: A framework for Bayesian multi-object tracking
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
